# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Swift ${{ matrix.swift }}
    strategy:
      matrix:
        swift: ["5.8", "5.9", "5.10"]
    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4

    - name: Setup Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: ${{ matrix.swift }}

    - if: ${{ matrix.swift == '5.8' }}
      name: Xcode Select
      run: sudo xcode-select -s /Applications/Xcode_14.3.1.app

    - name: Build
      run: swift build -v

    - name: Run tests
      run: swift test -v
